IV-1: Cqecw

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,20 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 npm run lint
+
+#!/bin/sh
+
+# Retrieve author information as Git sees it while commiting
+AUTHORINFO=$(git var GIT_AUTHOR_IDENT) || exit 1
+NAME=$(printf '%s\n\n' "${AUTHORINFO}" | sed -n 's/^\(.*\) <.*$/\1/p')
+EMAIL=$(printf '%s\n\n' "${AUTHORINFO}" | sed -n 's/^.* <\(.*\)> .*$/\1/p')
+REMOTE_ORIGIN_URL=$(git remote get-url origin)
+
+# If we're trying to commit to repo with not allowed email
+if [[ $REMOTE_ORIGIN_URL != *"https://github.com/amandrichenko/tic-tac-toe.git"* ]] && [[ $EMAIL == *"cec"* ]]; then
+    printf "NAME: %s\n" "${NAME}"
+    printf "EMAIL: %s\n" "${EMAIL}"
+    printf "REMOTE URL: %s\n" "${REMOTE_ORIGIN_URL}"
+    echo "\nOh, please stop. I cannot allow you to commit with your current email: ${EMAIL}\n"
+    exit 1;
+fi
